In [1]:
##http://archive.ics.uci.edu/ml/machine-learning-databases/00519/
    
    
#Thirteen (13) clinical features:

#- age: age of the patient (years)
#- anaemia: decrease of red blood cells or hemoglobin (boolean)
#- high blood pressure: if the patient has hypertension (boolean)
#- creatinine phosphokinase (CPK): level of the CPK enzyme in the blood (mcg/L)
#- diabetes: if the patient has diabetes (boolean)
#- ejection fraction: percentage of blood leaving the heart at each contraction (percentage)
#- platelets: platelets in the blood (kiloplatelets/mL)
#- sex: woman or man (binary)
#- serum creatinine: level of serum creatinine in the blood (mg/dL)
#- serum sodium: level of serum sodium in the blood (mEq/L)
#- smoking: if the patient smokes or not (boolean)
#- time: follow-up period (days)
#- [target] death event: if the patient deceased during the follow-up period (boolean)

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("heart_failure_clinical_records_dataset.csv")

In [4]:
df.head(5)

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
0,75.0,0,582,0,20,1,265000.00,1.9,130,1,0,4,1
1,55.0,0,7861,0,38,0,263358.03,1.1,136,1,0,6,1
2,65.0,0,146,0,20,0,162000.00,1.3,129,1,1,7,1
3,50.0,1,111,0,20,0,210000.00,1.9,137,1,0,7,1
4,65.0,1,160,1,20,0,327000.00,2.7,116,0,0,8,1

In [15]:
df.drop(['diabetes'],axis=1)

,age,anaemia,creatinine_phosphokinase,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
0,75.0,0,582,20,1,265000.00,1.9,130,1,0,4,1
1,55.0,0,7861,38,0,263358.03,1.1,136,1,0,6,1
2,65.0,0,146,20,0,162000.00,1.3,129,1,1,7,1
3,50.0,1,111,20,0,210000.00,1.9,137,1,0,7,1
4,65.0,1,160,20,0,327000.00,2.7,116,0,0,8,1
...,...,...,...,...,...,...,...,...,...,...,...,...
294,62.0,0,61,38,1,155000.00,1.1,143,1,1,270,0
295,55.0,0,1820,38,0,270000.00,1.2,139,0,0,271,0
296,45.0,0,2060,60,0,742000.00,0.8,138,0,0,278,0
297,45.0,0,2413,38,0,140000.00,1.4,140,1,1,280,0
298,50.0,0,196,45,0,395000.00,1.6,136,1,1,285,0

In [23]:
data = df.values
X = data[:, 2:4]
y = data[:, -1].reshape(-1, 1)

In [24]:
print(X)

[[5.820e+02 0.000e+00]
 [7.861e+03 0.000e+00]
 [1.460e+02 0.000e+00]
 [1.110e+02 0.000e+00]
 [1.600e+02 1.000e+00]
 [4.700e+01 0.000e+00]
 [2.460e+02 0.000e+00]
 [3.150e+02 1.000e+00]
 [1.570e+02 0.000e+00]
 [1.230e+02 0.000e+00]
 [8.100e+01 0.000e+00]
 [2.310e+02 0.000e+00]
 [9.810e+02 0.000e+00]
 [1.680e+02 0.000e+00]
 [8.000e+01 0.000e+00]
 [3.790e+02 0.000e+00]
 [1.490e+02 0.000e+00]
 [5.820e+02 0.000e+00]
 [1.250e+02 0.000e+00]
 [5.820e+02 1.000e+00]
 [5.200e+01 0.000e+00]
 [1.280e+02 1.000e+00]
 [2.200e+02 0.000e+00]
 [6.300e+01 1.000e+00]
 [5.820e+02 1.000e+00]
 [1.480e+02 1.000e+00]
 [1.120e+02 0.000e+00]
 [1.220e+02 1.000e+00]
 [6.000e+01 0.000e+00]
 [7.000e+01 1.000e+00]
 [5.820e+02 1.000e+00]
 [2.300e+01 0.000e+00]
 [2.490e+02 1.000e+00]
 [1.590e+02 1.000e+00]
 [9.400e+01 1.000e+00]
 [5.820e+02 1.000e+00]
 [6.000e+01 1.000e+00]
 [8.550e+02 1.000e+00]
 [2.656e+03 1.000e+00]
 [2.350e+02 1.000e+00]
 [5.820e+02 0.000e+00]
 [1.240e+02 1.000e+00]
 [5.710e+02 1.000e+00]
 [1.270e+02 1.000e+00]
 [5.880e+02 1.000e+00]
 [5.820e+02 1.000e+00]
 [1.380e+03 0.000e+00]
 [5.820e+02 1.000e+00]
 [5.530e+02 0.000e+00]
 [1.290e+02 0.000e+00]
 [5.770e+02 0.000e+00]
 [9.100e+01 0.000e+00]
 [3.964e+03 1.000e+00]
 [6.900e+01 1.000e+00]
 [2.600e+02 1.000e+00]
 [3.710e+02 0.000e+00]
 [7.500e+01 0.000e+00]
 [6.070e+02 0.000e+00]
 [7.890e+02 0.000e+00]
 [3.640e+02 1.000e+00]
 [7.702e+03 1.000e+00]
 [3.180e+02 0.000e+00]
 [1.090e+02 0.000e+00]
 [5.820e+02 0.000e+00]
 [5.820e+02 0.000e+00]
 [6.800e+01 0.000e+00]
 [2.500e+02 1.000e+00]
 [1.100e+02 0.000e+00]
 [1.610e+02 0.000e+00]
 [1.130e+02 1.000e+00]
 [1.480e+02 0.000e+00]
 [5.820e+02 1.000e+00]
 [5.882e+03 0.000e+00]
 [2.240e+02 1.000e+00]
 [5.820e+02 0.000e+00]
 [4.700e+01 0.000e+00]
 [9.200e+01 0.000e+00]
 [1.020e+02 1.000e+00]
 [2.030e+02 1.000e+00]
 [3.360e+02 0.000e+00]
 [6.900e+01 0.000e+00]
 [5.820e+02 0.000e+00]
 [7.600e+01 1.000e+00]
 [5.500e+01 0.000e+00]
 [2.800e+02 1.000e+00]
 [7.800e+01 0.000e+00]
 [4.700e+01 0.000e+00]
 [6.800e+01 1.000e+00]
 [8.400e+01 1.000e+00]
 [1.150e+02 0.000e+00]
 [6.600e+01 1.000e+00]
 [8.970e+02 1.000e+00]
 [5.820e+02 0.000e+00]
 [1.540e+02 0.000e+00]
 [1.440e+02 1.000e+00]
 [1.330e+02 0.000e+00]
 [5.140e+02 1.000e+00]
 [5.900e+01 0.000e+00]
 [1.560e+02 1.000e+00]
 [6.100e+01 1.000e+00]
 [3.050e+02 0.000e+00]
 [5.820e+02 0.000e+00]
 [8.980e+02 0.000e+00]
 [5.209e+03 0.000e+00]
 [5.300e+01 0.000e+00]
 [3.280e+02 0.000e+00]
 [7.480e+02 0.000e+00]
 [1.876e+03 1.000e+00]
 [9.360e+02 0.000e+00]
 [2.920e+02 1.000e+00]
 [1.290e+02 0.000e+00]
 [6.000e+01 0.000e+00]
 [3.690e+02 1.000e+00]
 [1.430e+02 0.000e+00]
 [7.540e+02 1.000e+00]
 [4.000e+02 0.000e+00]
 [9.600e+01 1.000e+00]
 [1.020e+02 0.000e+00]
 [1.130e+02 1.000e+00]
 [5.820e+02 0.000e+00]
 [7.370e+02 0.000e+00]
 [6.800e+01 1.000e+00]
 [9.600e+01 1.000e+00]
 [5.820e+02 0.000e+00]
 [5.820e+02 0.000e+00]
 [3.580e+02 0.000e+00]
 [1.680e+02 1.000e+00]
 [2.000e+02 1.000e+00]
 [2.480e+02 0.000e+00]
 [2.700e+02 1.000e+00]
 [1.808e+03 0.000e+00]
 [1.082e+03 1.000e+00]
 [7.190e+02 0.000e+00]
 [1.930e+02 0.000e+00]
 [4.540e+03 0.000e+00]
 [5.820e+02 0.000e+00]
 [5.900e+01 1.000e+00]
 [6.460e+02 0.000e+00]
 [2.810e+02 1.000e+00]
 [1.548e+03 0.000e+00]
 [8.050e+02 0.000e+00]
 [2.910e+02 0.000e+00]
 [4.820e+02 1.000e+00]
 [8.400e+01 0.000e+00]
 [9.430e+02 0.000e+00]
 [1.850e+02 0.000e+00]
 [1.320e+02 0.000e+00]
 [1.610e+03 0.000e+00]
 [5.820e+02 0.000e+00]
 [2.261e+03 0.000e+00]
 [2.330e+02 0.000e+00]
 [3.000e+01 1.000e+00]
 [1.150e+02 0.000e+00]
 [1.846e+03 1.000e+00]
 [3.350e+02 0.000e+00]
 [2.310e+02 1.000e+00]
 [5.800e+01 0.000e+00]
 [2.500e+02 0.000e+00]
 [9.100e+02 0.000e+00]
 [1.290e+02 0.000e+00]
 [7.200e+01 0.000e+00]
 [1.300e+02 0.000e+00]
 [5.820e+02 0.000e+00]
 [2.334e+03 1.000e+00]
 [2.442e+03 1.000e+00]
 [7.760e+02 1.000e+00]
 [1.960e+02 0.000e+00]
 [6.600e+01 1.000e+00]
 [5.820e+02 1.000e+00]
 [8.350e+02 0.000e+00]
 [5.820e+02 1.000e+00]
 [3.966e+03 0.000e+00]
 [1.710e+02 0.000e+00]
 [1.150e+02 0.000e+00]
 [1.980e+02 1.000e+00]
 [9.500e+01 0.000e+00]
 [1.419e+03 0.000e+00]
 [6.900e+01 0.000e+00]
 [1.220e+02 1.000e+00]
 [8.350e+02 0.000e+00]
 [4.780e+02 1.000e+00]
 [1.760e+02 1.000e+00]
 [3.950e+02 1.000e+00]
 [9.900e+01 0.000e+00]
 [1.450e+02 0.000e+00]
 [1.040e+02 1.000e+00]
 [5.820e+02 0.000e+00]
 [1.896e+03 1.000e+00]
 [1.510e+02 1.000e+00]
 [2.440e+02 0.000e+00]
 [5.820e+02 1.000e+00]
 [6.200e+01 0.000e+00]
 [1.210e+02 1.000e+00]
 [2.310e+02 1.000e+00]
 [5.820e+02 0.000e+00]
 [4.180e+02 0.000e+00]
 [5.820e+02 1.000e+00]
 [1.670e+02 0.000e+00]
 [5.820e+02 1.000e+00]
 [1.211e+03 1.000e+00]
 [1.767e+03 0.000e+00]
 [3.080e+02 1.000e+00]
 [9.700e+01 0.000e+00]
 [5.900e+01 0.000e+00]
 [6.400e+01 0.000e+00]
 [1.670e+02 1.000e+00]
 [1.010e+02 0.000e+00]
 [2.120e+02 0.000e+00]
 [2.281e+03 1.000e+00]
 [9.720e+02 1.000e+00]
 [2.120e+02 1.000e+00]
 [5.820e+02 0.000e+00]
 [2.240e+02 0.000e+00]
 [1.310e+02 1.000e+00]
 [1.350e+02 0.000e+00]
 [5.820e+02 0.000e+00]
 [1.202e+03 0.000e+00]
 [4.270e+02 0.000e+00]
 [1.021e+03 1.000e+00]
 [5.820e+02 1.000e+00]
 [5.820e+02 0.000e+00]
 [1.180e+02 0.000e+00]
 [8.600e+01 0.000e+00]
 [5.820e+02 0.000e+00]
 [5.820e+02 1.000e+00]
 [6.750e+02 1.000e+00]
 [5.700e+01 0.000e+00]
 [2.794e+03 0.000e+00]
 [5.600e+01 0.000e+00]
 [2.110e+02 0.000e+00]
 [1.660e+02 0.000e+00]
 [9.300e+01 0.000e+00]
 [1.290e+02 0.000e+00]
 [7.070e+02 0.000e+00]
 [5.820e+02 0.000e+00]
 [1.090e+02 0.000e+00]
 [1.190e+02 0.000e+00]
 [2.320e+02 0.000e+00]
 [7.200e+02 1.000e+00]
 [1.800e+02 0.000e+00]
 [8.100e+01 1.000e+00]
 [5.820e+02 1.000e+00]
 [9.000e+01 0.000e+00]
 [1.185e+03 0.000e+00]
 [5.820e+02 1.000e+00]
 [8.000e+01 1.000e+00]
 [2.017e+03 0.000e+00]
 [1.430e+02 0.000e+00]
 [6.240e+02 0.000e+00]
 [2.070e+02 1.000e+00]
 [2.522e+03 0.000e+00]
 [5.720e+02 1.000e+00]
 [2.450e+02 0.000e+00]
 [8.800e+01 1.000e+00]
 [4.460e+02 0.000e+00]
 [1.910e+02 1.000e+00]
 [3.260e+02 0.000e+00]
 [1.320e+02 1.000e+00]
 [6.600e+01 1.000e+00]
 [5.600e+01 0.000e+00]
 [6.600e+01 0.000e+00]
 [6.550e+02 0.000e+00]
 [2.580e+02 1.000e+00]
 [1.570e+02 1.000e+00]
 [5.820e+02 1.000e+00]
 [2.980e+02 0.000e+00]
 [1.199e+03 0.000e+00]
 [1.350e+02 1.000e+00]
 [5.820e+02 1.000e+00]
 [5.820e+02 1.000e+00]
 [5.820e+02 1.000e+00]
 [5.820e+02 1.000e+00]
 [2.130e+02 0.000e+00]
 [6.400e+01 0.000e+00]
 [2.570e+02 1.000e+00]
 [5.820e+02 0.000e+00]
 [6.180e+02 0.000e+00]
 [5.820e+02 1.000e+00]
 [1.051e+03 1.000e+00]
 [8.400e+01 1.000e+00]
 [2.695e+03 1.000e+00]
 [5.820e+02 0.000e+00]
 [6.400e+01 0.000e+00]
 [1.688e+03 0.000e+00]
 [5.400e+01 0.000e+00]
 [1.700e+02 1.000e+00]
 [2.530e+02 0.000e+00]
 [5.820e+02 1.000e+00]
 [8.920e+02 1.000e+00]
 [3.370e+02 0.000e+00]
 [6.150e+02 1.000e+00]
 [3.200e+02 0.000e+00]
 [1.900e+02 1.000e+00]
 [1.030e+02 1.000e+00]
 [6.100e+01 1.000e+00]
 [1.820e+03 0.000e+00]
 [2.060e+03 1.000e+00]
 [2.413e+03 0.000e+00]
 [1.960e+02 0.000e+00]]

In [25]:
## sử dụng thư viện MinMaxScaler
from sklearn.preprocessing import MinMaxScaler
Xscaler = MinMaxScaler()
Xscaler.fit(X)

X = Xscaler.fit_transform(X)  ## Scale dữ liệu của x
yscaler = MinMaxScaler()
yscaler.fit(y)
y = yscaler.fit_transform(y)  ## Scale dữ liệu của y

In [26]:
print('X: ',X[0:5])
print('\nY: ',y[0:5])

X:  [[0.07131921 0.        ]
 [1.         0.        ]
 [0.01569278 0.        ]
 [0.01122735 0.        ]
 [0.01747895 1.        ]]

Y:  [[1.]
 [1.]
 [1.]
 [1.]
 [1.]]

In [27]:
print(X.shape)

(299, 2)

In [28]:
print(y.shape)

(299, 1)

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.8)


### test 20%, train 80%
y_train = y_train.ravel()
y_test = y_test.ravel()

print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(239, 2) (239,)
(60, 2) (60,)

In [30]:
from sklearn import metrics
from sklearn.metrics import classification_report

from sklearn.neighbors import  KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier

#KNN
KNN = KNeighborsClassifier(n_neighbors = 3)
KNN.fit(X_train, y_train)
y_predict_KNN = KNN.predict(X_test)
score_KNN = metrics.accuracy_score(y_predict_KNN,y_test)
print("Accuracy of KNN: ",score_KNN)
print(classification_report(y_test, y_predict_KNN))
print('------------------------------------------------------------')

#SVM
svm = SVC(kernel='linear')
svm.fit(X_train,y_train)
y_predict_svm = svm.predict(X_test)
score_svm = metrics.accuracy_score(y_predict_svm,y_test)
print("Accuracy of SVM: ",score_svm)
print(classification_report(y_test,y_predict_svm))
print('------------------------------------------------------------')

#NB
NB = GaussianNB()
NB.fit(X_train,y_train)
y_predict_NB = NB.predict(X_test)
score_NB = metrics.accuracy_score(y_predict_NB,y_test)
print("Accuracy of NB: ", score_NB)
print(classification_report(y_test,y_predict_NB))
print('------------------------------------------------------------')

#MLPC
MLPC = MLPClassifier(hidden_layer_sizes=(20, 20, 20))
MLPC.fit(X_train, y_train)
y_predict_MLPC = MLPC.predict(X_test)
score_MLPC = metrics.accuracy_score(y_predict_MLPC,y_test)
print("Accuracy of MLPC: ", score_MLPC)
print(classification_report(y_test,y_predict_MLPC))

Accuracy of KNN:  0.6
              precision    recall  f1-score   support

         0.0       0.74      0.67      0.71        43
         1.0       0.33      0.41      0.37        17

    accuracy                           0.60        60
   macro avg       0.54      0.54      0.54        60
weighted avg       0.63      0.60      0.61        60

------------------------------------------------------------
Accuracy of SVM:  0.7166666666666667
              precision    recall  f1-score   support

         0.0       0.72      1.00      0.83        43
         1.0       0.00      0.00      0.00        17

    accuracy                           0.72        60
   macro avg       0.36      0.50      0.42        60
weighted avg       0.51      0.72      0.60        60

------------------------------------------------------------
Accuracy of NB:  0.6833333333333333
              precision    recall  f1-score   support

         0.0       0.71      0.93      0.81        43
         1.0       0.25      0.06      0.10        17

    accuracy                           0.68        60
   macro avg       0.48      0.49      0.45        60
weighted avg       0.58      0.68      0.61        60

------------------------------------------------------------
Accuracy of MLPC:  0.7166666666666667
              precision    recall  f1-score   support

         0.0       0.72      1.00      0.83        43
         1.0       0.00      0.00      0.00        17

    accuracy                           0.72        60
   macro avg       0.36      0.50      0.42        60
weighted avg       0.51      0.72      0.60        60

C:\Users\nkhoi\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
C:\Users\nkhoi\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\nkhoi\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\nkhoi\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\nkhoi\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\nkhoi\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\nkhoi\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))